### PR TITLE
BUG FIX: [] operator not supported for strings

### PR DESCRIPTION
**Pull request by drAlberT**
When setting custom `$upload_url_path` WP requires it **without** trailing slash, but doing so raises a bug as an array is initialized as empty string instead of empty array.

```
2019/01/23 09:38:39 [error] 8156#8156: *671693 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /srv/wp-content/plugins/sitepress-multilingual-cms/classes/utilities/class-wpml-flags.php:140
```

### CODE REVIEW

**Comment by drAlberT** [comment]
@remcotolsma please include this fix in the upcoming release .. it is very important for me.

Thanks

**Comment by drAlberT** [comment]
@remcotolsma sorry, I read only now the description on this repo ..

can you tell me how can open a PR or a bug to the vendor site?

**Comment by remcotolsma** [comment]
No sorry, i think you have to contact https://wpml.org/home/contact-us/contact-form/ for this.

**Comment by drAlberT** [comment]
yep, done. Thanks

**Pull request closed without merging**
